package com.debi.socialmediaapp.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Entity class representing the USERS table in the database.
 * This class is used to map the table fields to Java object fields.
 *
 * @author ahmedynah
 * @version 1.0.0
 * @since 1.0.0
 */
@Data // Lombok annotation to generate getters, setters, equals, hashCode, and toString methods
@Entity // Marks this class as a JPA entity
@NoArgsConstructor // Generates a no-argument constructor
@AllArgsConstructor // Generates an all-argument constructor
@Table(name = "USERS") // Maps this class to the USERS table in the database
public class Users {

    /**
     * Primary key for the USERS table.
     * It is auto-generated by the database using the IDENTITY strategy.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies the primary key generation strategy
    @Column(name = "ID") // Maps this field to the ID column in the USERS table
    private long id;

    /**
     * Column representing the username of the user.
     */
    @Column(name = "USERNAME") // Maps this field to the USERNAME column in the USERS table
    private String username;

    /**
     * Column representing the password of the user.
     */
    @Column(name = "PASSWORD") // Maps this field to the PASSWORD column in the USERS table
    private String password;
}
