package com.debi.socialmediaapp.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Entity class representing the USERS table in the database.
 * This class is used to map the table fields to Java object fields.
 *
 * @author ahmedynah
 * @version 1.0.0
 * @since 1.0.0
 */
@Data // Lombok annotation to generate getters, setters, equals, hashCode, and toString methods
@Entity // Marks this class as a JPA entity
@NoArgsConstructor // Generates a no-argument constructor
@AllArgsConstructor // Generates an all-argument constructor
@Table(name = "users") // Maps this class to the USERS table in the database
public class User {

    /**
     * Primary key for the USERS table.
     * It is auto-generated by the database using the IDENTITY strategy.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies the primary key generation strategy
    @Column(name = "id") // Maps this field to the ID column in the USERS table
    private long id;

    /**
     * Column representing the first_name of the user.
     */
    @Column(name = "first_name") // Maps this field to the USERNAME column in the USERS table
    private String firstName;


    /**
     * Column representing the last_name of the user.
     */
    @Column(name = "last_name") // Maps this field to the USERNAME column in the USERS table
    private String lastName;

    /**
     * Column representing the email of the user.
     */
    @Column(name = "email") // Maps this field to the USERNAME column in the USERS table
    private String email;


    /**
     * Column representing the password of the user.
     */
    @Column(name = "PASSWORD") // Maps this field to the PASSWORD column in the USERS table
    private String password;


    public User(String firstName, String lastName, String email, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
    }

}
